### ISSUE TITLE
chinese ?

### ISSUE THREAD

**Issue by youling257** [zhaofengli/iwork8#1]
your iWork8 ，Z3735D or z3735f ?

**Comment by zhaofengli** [comment]
Z3735F, according to [`/proc/cpuinfo`](https://github.com/zhaofengli/iwork8/blob/master/cpuinfo).

**Comment by youling257** [comment]
我想解决的是Androidx86 6.0.1，Androidx86 cm13，z3735f的驱动问题。没声音、亮度不能调节，rtl8723bs蓝牙不能工作，wifi可以，电源管理也不能工作。触摸屏gsl3676，可以工作
这是Androidx86 cm13， https://drive.google.com/folderview?id=0B9vJ9JSuyPijWTRpU2VLUkVhYkE&usp=drive_web&tid=0B9vJ9JSuyPijaVNZZHNuaDJDWUE#list

**Comment by youling257** [comment]
声音问题，你看看这里https://github.com/burzumishi/linux-baytrail-flexx10
The device is an Intel SST Audio / Realtek RT5640. The firmware can be installed with:

# apt-get install firmware-intel-sound

However a manual configuration of the device is still required. It is possible to do it using alsactl (available in the package alsa-utils) and a proper configuration file. The T100 Ubuntu community on G+ has many configuration files you can try but this one seems to work well. Download and apply the configuration file in this way:

# cp asound.state /var/lib/alsa/

# alsactl restore

# sh set-alsa-bytcr-rt5640.sh

This will enable your sound card, at this moment I only got some crakles at bootand login time.

[  994.246832]  Baytrail Audio Port: sst: error code = -22
[  994.246840] bytcr_rt5640 bytcr_rt5640: BUG: , pos = -22, buffer size = 203830, period size = 1199
[  994.246863]  Baytrail Audio Port: sst: error code = -22
[  994.246870] bytcr_rt5640 bytcr_rt5640: BUG: , pos = -22, buffer size = 203830, period size = 1199

All these firmware errors will increase your kernel boot time.

Please be aware that there are reports indicating that in some cases the sound can be distorted and the speakers can be even damaged if the volume is high. Be careful in doing tests. Headphones work too but switching from the speaker is not automatic, it can be done using the audio manager of the DE or a dedicated application like pavucontrol.

For the linux kernel 3.16 in Debian Jessie use the firmware and the alsa configuration files available here. However, as suggested in the important notes above, it is not advisable to use this kernel due to a lot of components unsupported

**Comment by youling257** [comment]
触摸屏问题，https://github.com/onitake/gslx680-acpi

**Comment by youling257** [comment]
Androidx86 源码https://sourceforge.net/p/android-x86/manifest/ci/marshmallow-x86/tree
Androidx86内核树https://sourceforge.net/p/android-x86/kernel/ci/kernel-4.4/tree/

**Comment by zhaofengli** [comment]
声音的话我待会试试。触摸屏本来就可以用（我的是双系统版，如果你用旗舰版的话，实在找不到 GSL3670 的固件）。

**Comment by youling257** [comment]
双系统，那是Android  ia，我昂达v891w也是双系统Android ia 4.4.4
我有两台v891w，另一台研究Androidx86原生和cm13，那个Androidx86内核树，有人告诉了我编译方法

**Comment by zhaofengli** [comment]
嗯，对安卓的话没什么兴趣，正常内核的话 make-kpkg 就可以编译。我的 iWork 8 还在充电，稍后试一下源里面的固件。

**Comment by youling257** [comment]
在平板上也装上了Ubuntu，用来编译Androidx86内核，声音、亮度、电量显示都要用脚本，这在Android上怎么用

**Comment by youling257** [comment]
蓝牙问题，看这里https://github.com/Manouchehri/vi8/blob/master/Ubuntu_instructions.md
The WiFi drivers indeed are also drivers for Bluetooth, but getting Bluetooth working is a bit difficult. You need to patch your kernel with this patch. Then use this program to add the firmware to your Linux install and also there is a script that needs to be run each boot to turn on the Bluetooth module.

Androidx86蓝牙问题，在这里https://groups.google.com/forum/#!topic/android-x86/kPBpj3CoXW4 ，目前没有解决

**Comment by zhaofengli** [comment]
编译内核的话还是电脑上来吧，寨板性能实在太渣 🙈

音频试了一下，源里的不行（我在用 Debian stretch，下到的包是 [firmware-intel-sound_20160110-1_all.deb](http://ftp.cn.debian.org/debian/pool/non-free/f/firmware-nonfree/firmware-intel-sound_20160110-1_all.deb)）。我在 [`firmware`](https://github.com/zhaofengli/iwork8/tree/master/firmware) 中附带了一个 ELF 格式的固件（原 Android 系统里拷贝出来的），但新内核的上游驱动已经不支持这个格式了。[这个帖子](http://thread.gmane.org/gmane.linux.alsa.devel/134554)上有人做出了[一个转换器](https://git.ao2.it/sst_elf_firmware_convert.git/)，但测试并不能生成可用的固件。

关于蓝牙，我将 ID 加入 rfkill 的列表里之后的确探测到了蓝牙设备，但无法进行配对。有点神奇 🙈 

亮度的话我最近没有看，不知道上游驱动有没有添加支持。`xrandr` 的方法是纯软件的，就是像护目镜 app 一样，不会真正改变亮度。

关于电量显示的话，最好还是试试内核里的 `axp288_fuel_gauge` 驱动能不能用，因为我做的脚本没办法优雅地集成到系统。

**Comment by youling257** [comment]
root@youling257-ONDA-Tablet:/home/youling257/桌面/android-x86-kernel-d492a48442a
e0e068d8749f7c2ab828806c6c298# make android-x86_defconfig
root@youling257-ONDA-Tablet:/home/youling257/桌面/android-x86-kernel-d492a48442a
e0e068d8749f7c2ab828806c6c298# make
root@youling257-ONDA-Tablet:/home/youling257/桌面/android-x86-kernel-d492a48442a
e0e068d8749f7c2ab828806c6c298# make targz-pkg -i

寨板上Ubuntu编译Androidx86内核，3个小时编译完成。还是寨板上，time make -j8，55分钟，time make -j8 targz-pkg -i，5分钟，-j4也是一样的时间

**Comment by zhaofengli** [comment]
我电脑上的话初次编译需要一个钟左右，以后的话十分钟（A8-5600K，8GB 内存，设置 5 线程）。

**Comment by youling257** [comment]
Androidx86 cm13，内核版本4.4.4，没有/sys/module/test_power这个目录，怎么办？
https://groups.google.com/forum/#!topic/android-x86/NTaCu26ehsI
spin877     4月18日（22 小时前）you should build a kernel with
CONFIG_TEST_POWER=m
CONFIG_I2C_CHARDEV=m
set or m , or y, and the same
这什么意思？

**Comment by youling257** [comment]
话说那个https://github.com/hadess/rtl8723bs ，下载下来解压缩，ubuntu15.10，终端命令make和make install，
结果呢，wifi一直连接中，根本连接不了，连接中、连接中，连接中24小时都连不上，有时偶尔能连接上；我就不信就我一个人有这问题，所有人用https://github.com/hadess/rtl8723bs 这里的wifi驱动，秒连？ 真气人
Androidx86的4.0.9内核和4.4.4内核包含了rtl8723bs，这个可以秒连wifi

**Comment by zhaofengli** [comment]
抱歉回答晚了。

关于 `test_power`，你需要在内核配置（`.config`）里面加入那两条配置，就可以使用 `battery.sh` 了（脚本里的 `modprobe test_power` 会自动帮你加载这个模块）。

至于 Wi-Fi 的问题，你需要看一下日志，找一下是哪一个环节出了问题。对了，你有应用 `rtl8723bs` 仓库里的内核补丁吧？

**Comment by youling257** [comment]
CONFIG_TEST_POWER=m，CONFIG_I2C_CHARDEV=m加在arch/x86/configs/android-x86_64_defconfig，也是一样的吧。加在什么位置？config 6000多行
找到了这几行# CONFIG_GENERIC_ADC_BATTERY is not set，# CONFIG_TEST_POWER is not set，怎么改？
还有这里# I2C support
#
CONFIG_I2C=y
CONFIG_ACPI_I2C_OPREGION=y
CONFIG_I2C_BOARDINFO=y
CONFIG_I2C_COMPAT=y
CONFIG_I2C_CHARDEV=m
CONFIG_I2C_MUX=m

**Comment by zhaofengli** [comment]
查了一下，Android-x86 的配置位置太奇葩了。你在那个文件里面搜索这两个符号名，修改对应的位置，然后重新编译内核试试？编译普通的 Linux 内核的时候，配置一般是放在源码目录的 `.config` 文件里面的。

**Comment by zhaofengli** [comment]
如果对应的行是 not set 的注释，将它替换掉。

**Comment by youling257** [comment]
修改android-x86_64_defconfig没用，make android-x86_64_defconfig生成内核树根目录下的.config还是test_power not set，还得改.config，# CONFIG_TEST_POWER is not set改成CONFIG_TEST_POWER=m

之前修改android-x86_64_defconfig，没有去掉#，所以.config还是not set。所以修改android-x86_64_defconfig就行了，去掉#

**Comment by youling257** [comment]
read battery voltage    79h, 78h    0 mV -> 000h,   1.1 mV/bit  FFFh -> 4.5045 V ，改成多少？
aida64显示我这个，18574mWh，4.100 V

u0_a49@android_x86:/ $ su
root@android_x86:/ # sh /system/etc/init.d/2.sh
i2cget: read failed: Remote I/O error
/system/etc/init.d/2.sh[16]: [: 0: unexpected operator/operand
i2cget: read failed: Remote I/O error
/system/etc/init.d/2.sh[16]: [: 0: unexpected operator/operand
i2cget: read failed: Remote I/O error
/system/etc/init.d/2.sh[16]: [: 0: unexpected operator/operand
/dev/i2c-dev4
Battery level: 94%
Charging current: 0 (discharging)
Current Charge = 0mA
Current DisCharge = 1568mA
Battery voltage = 3632mV

Battery level: 93%
Charging current: 0 (discharging)
Current Charge = 0mA
Current DisCharge = 1744mA
Battery voltage = 3616mV

**Comment by KiokuCoder** [comment]
菜鸡默默路过，大神还有在折腾吗？我想在我的iwork8上安装linux，貌似之前版本有带触摸驱动，最新的旗舰版触摸驱动没找到，不知道你们有没有
